language: scala
install:
  - pip install --user codecov

scala:
   - 2.11.8
   - 2.12.0

jdk:
- oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - travis_wait 60 scripts/travis-publish.sh

sudo: false