language: scala
install:
  - pip install --user codecov

scala:
   - 2.11.8
   - 2.12.0

jdk:
- oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

env:
  global:
  - secure: oPHeduifk/UdQLWWpCH+SU5oVJZkmmt7LwyvQ2wTH520+Y0NPZ8sxeVaF4rGmx2e2vqN4QAR718HdkQ/GnvBaXBnv1jOQDJho9fxCPgbqo+4JtKhuUNSBH1AGTQVO6tKVfPTWBche+1dgp63a5OMpAJjTeYhRQ63nE1gyB0QVHj232GoyOD5AOo2fSgR78hD8UhIDru3C8gKywL/QjPUcRS3QtkMeSsWavtcvxxNE1IWJxiqPKrn+8MsP3fa+mBxyChRyKfIt0AG9teJcw3Hb+xO7DcouQyE027KNbYQBRKTIezg0uGp9Pxe/mlXxy/+O22EFWs0ImHm4nX1ca0ssnnjYaOdWVOwFz33Ax+0YWqYO3/EXoWVDEeP0MxDAXBS11DDVXp93SrPCuqoejYM8ksKnEQuXP3UirhfWvjRF0R2w0m5u7SW92lLA1asKa+XKSTV0pTMpDE0WvUhpPoqbeXhhfBleYa4AvJRodlro+ii0ggQOgoSaAchAsDdV8wCHheeUZESzeL7VYoM10XKvy0H81rVScmKuN+uWBbkQrMZHd9rdcbR8OhcvNZ9Vr/H4Du3/3B1UfcLgLgDRnUaDYyGxe8R0J97c7wP9tJ3OvvG8Eyzjbgh3dzDGBMw/IrZ2RRubwpGE31baiHl9JklI0SiGx1EKOmA/IwyzgoJOAM=
  
  - secure: cyriW1dx+Q1u8FxFL2tWNvdmarKcXGB/b2CTpaqui8YkFhzfnxuJYY7FWHKnynyrQdfbBW+0WEar/nmSNSNjIC6o2wKnkPsIIBU9k1bL8gs9tct0Z2Um7mUp5E3dxt6wJo4xVn+MZJ+URvAUuNKOviMCel2tEXomTAC2Z6dG1h+vUr/yoMh56vD1rknWBXZNf225aaCb82C7XavuELZn7mUDeQB3HS86urpkAdErkOKf0Dvw0dIqpp7IyUHWo0+CQ/jFnBpGstgpbIMist6JK7VnadQfd3+9hcmuY7pNo7mpykmti1XgBQ+XWBly/h1lbvxj+KWCiYrGCxulGf1LKGTAa0fWSTXAxBTFcN/ZbAoehzncPHXsD0RyZk3QP3+HdY3esZOAEAYTUNNTLcSM0bZpX3QG4SggoBgcziM/lsYZTlPmDjozu+2D5EKZitTpRQMUh/8UrLqj168N4p4Hvb+yxGHTdUSfSQJ3dhX+um5WklxQdY7XP5S3ZpJGGY2znGvt1dPba5/ECFslKFIEl9HAay+MifFV3buTqcMoj5zrwOpX5/lzlZOSsnPhjZNZBEQAoHYArNIa2F592ST5TLAufaFr1gxpdynAlk1BwUS3SfWkIS5pfSDcNaDs9xTd8N0voBEoMW5z+F88oJmAe85U372fOkeBHbkxWTxRF9Y=

script:
  - travis_wait 60 scripts/travis-publish.sh

sudo: false