language: scala
install:
- pip install --user codecov
scala:
- 2.11.12
- 2.12.7
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
env:
  global:
  - secure: C8Cz+wLFgAekCxAq4RhqMWbnDgQmrpwWP0wzRm036wTLd0WvJBA1Xy01Ke8wDor3hSulSlCM3kQyJwxt+jvo5dYyeAdUHyDoQe3BZ+W34VE2pJ5YixNH5U4NNdIrq1FFB17L1FzW00PzLSLDCj20+cdrDjj0fjpz1DLu0YgzRCgL1AXmKz85+NFumnXH6gokCyrQNvAg0+yvEh5nwAHGLGOKV5CHF7kssaJ/BU0Nre0hV2eFXSZa67MmxHUkLEGfzGk5WqnG1HtuLpP1g6jyXSTtveERpP8lRnoR9ZmnZmbPfWNA5RvvAzgr3NvhZr3LIlWzVHZbgmX39t9Fyme2XJvPlW91SOxPx/DVZPK1ZiAhiy+GTCKR609M5sfH8Mb6kHhJ4kerL1+Ew0k27Bx11s2de3XBQnyMmZ0/ehYb2pF4xe/cE0oyJFkSokFjIuRTG3RO35XWTghhne/P9uUm67KyW1VyMNU1RC3CJh95MHFb+sxe4s2gyBEIU2jpAm2fL/d9JctMqN6dtqlzFHAQfE63Z8qJPbU4KPuZd9ud4Z0vUATapuOV/3lRNyhcF87EJCXnaqXxrn9vlHaWIrrDD+/tTTDboQiqEX3c4uYbyv2MQKqrc+aK2sq3SJk7djwN7igQtfI1SgzR/97ajL2fQVTN8+PtgK7OUcl6TVQIyYY=
  - secure: WUY4lFR/hke7U9nkQz+VFDAYKdpnsz61kG+6KvyXoGbDt+ZEp+RJokkh1DTy+HDkEQNddw+fMj6/k1G6flOJCQ/QUOAh8uJBqsMWwpFHOFjcIp+nKnc/4n2UyAHCUlYQVFyQW2OYnUeNsOygcu9BDZOE4wTaiYCicIq35KmK5AfnCsq5+W6yq3QSp9nGzWEQoOUplQ/1hAe655FBpQtMJYLoCGrOH+OiU6VTKHtZSm/DX8YaRgav+DXs+7badpIlna591AwZvVPM8OU9gWX8hGJx98SgmBNqjtE17R6ds2kmI7JRnSk0smKrBUHr7fH7tyeQ8PQxsSqHoLCcQXsXZ10i5nqGqJgH8jNdQ4tQSZHdg2yBuAo4AAfW9bEC6+ucQLBO2t8PLJO8+TH08qBl2A5fiTuGBojIxLxmJSt1pvizrUp412U640oDwVIKmrVsWr7tMOdO4S0bAynKvbrDPqhT6pQuGI6ruEcP3edBwf02KmVi+TuK/qe4YXy5KkZmyW9oVTuCBXhkEoFv2dinboyt2NVNYH8xsIf2OPEYpuH9pR6WdpaVGe1tUoygPHpfK74ZRNuA3KS7M9Tv25JLjEZkA3HkttQQsa/eqe2k1iu64xv6Az7G7oQteimJJOPZQTQUkGEmKnnG5nCgqpVw93t1kWpnDJQ+GtLrcy0ZNik=
script:
- travis_wait 60 scripts/travis-publish.sh
sudo: false
