addSbtPlugin("com.typesafe"                      % "sbt-mima-plugin"       % "0.3.0")
addSbtPlugin("com.typesafe.sbt"                  % "sbt-git"               % "1.0.0")
addSbtPlugin("com.github.gseitz"                 % "sbt-release"           % "1.0.10")
addSbtPlugin("com.jsuereth"                      % "sbt-pgp"               % "1.0.0")
addSbtPlugin("org.xerial.sbt"                    % "sbt-sonatype"          % "2.3")
addSbtPlugin("org.scoverage"                     % "sbt-scoverage"         % "1.5.1")
